### PR TITLE
New vue3 template tag

### PR DESCRIPTION
**Pull request by bbonf**
This assumes the vue app is built and included elsewhere in the page.
It also assumes that `createApp` and the required components are available somewhere on the global namespace.

For example, in babex we have the following `main.ts` file that sets up the environment and is part of the vue app:
```typescript
import { createApp } from 'vue'
import AgendaCalendar from './components/agenda/AgendaCalendar.vue'
import AgendaHome from './components/agenda/AgendaHome.vue'
import CallHome from './components/invite/CallHome.vue'

// using object.defineProperty instead of window.foo to satisfy typescript
Object.defineProperty(window, 'createApp', {value: createApp});

// any component that is used via the django {% vue %} tag should be registered as a global
Object.defineProperty(window, 'babex', {
    value:
    {
        AgendaCalendar,
        AgendaHome,
        CallHome
    }
});
```

The django template tag is then used like so:
```python
{% load vue3 %}

{% vue MyComponent :some_prop=python_var :another_prop="a_js_var" @click="js_function" const_prop="foo" %}
```

### CODE REVIEW

**Comment by tymees** [comment]
Hm, I think there's some files missing.

To  make the templatetags loadable, shouldn't there be a apps.py at least so Django knows it's actually an app?

Also, the Vue 2 app has some provisions to autoload the required files. Is this something we want to recreate as well?

**Comment by bbonf** [comment]
Don't know about `apps.py`, but it works for me if I add 'cdh.vue3' in settings.py.

And about autoloading, that would be nice I guess. In our case it doesn't really matter if we load everything upfront in one template.

**Comment by tymees** [comment]
> Don't know about apps.py, but it works for me if I add 'cdh.vue3' in settings.py.

Interesting, Django might be generating one then....

> And about autoloading, that would be nice I guess. In our case it doesn't really matter if we load everything upfront in one template.

Yeah that's certainly possible; however for generic Vue components (like the upcoming list view) I'd prefer it if we could automate it for ease of use. It's not required, so I guess I'll see if it's worth it during my experimenting...

**Comment by tymees** [comment]
I've rebased this PR on the latest develop branch, but haven't looked at it more than that.

(Was needed because #58 changed the dir structure)

**Comment by tymees** [comment]
So I've finally looked at it, took me long enough.

In general I like the approach! However, I do see a problem with the HTML that the tag generates:

It injects 'unsafe inline' JS (raw JS inside the HTML doc). This will not work with apps that have a Content Security Policy which blocks unsafe inline JS. (And from a security standpoint, that _should_ be all our apps). So we have to work around that somehow. One way is to inject a 'nonce' into the script tag (similar to a CSRF, a token the browser gets from the server which the browser then can use to validate the contents of a script tag is not (maliciously) injected). However, getting that nonce in a template tag might be problematic, as it requires access to the 'request' object. 

Another would be to rewrite the code to use a (generic) JS file instead. We'd need to find a different way to pass the required data however, which we could do using data attributes on the div I think?

**Comment by bbonf** [comment]
Thanks for the comment, that's a good point.
I can look into it sometime soon

**Comment by bbonf** [comment]
@tymees  turned out to be quite simple: https://github.com/UiL-OTS-labs/django-vue3-tag/commit/2471b2d587c952efe72ef76ced4d47c435ee4afe
I'm not sure what's going with this PR, but we can keep the discussion here if you like.

**Comment by tymees** [comment]
I've pulled in the changes from that repo; I'll merge this now so I can start working on some components we need at portaldev

**Pull request merged**
